[2025-02-21 21:15:16,962: INFO: main: Welcome to custom log | created by Dharaneesh]
[2025-02-22 05:00:45,159: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 05:00:45,170: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 05:00:45,170: INFO: common: created directory at: artifacts]
[2025-02-22 05:00:45,170: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-22 05:02:35,110: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 05:02:35,117: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 05:02:35,123: INFO: common: created directory at: artifacts]
[2025-02-22 05:02:35,123: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-22 05:04:36,974: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 05:04:36,974: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 05:04:36,974: INFO: common: created directory at: artifacts]
[2025-02-22 05:04:36,982: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-22 05:06:43,950: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 05:06:43,950: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 05:06:43,958: INFO: common: created directory at: artifacts]
[2025-02-22 05:06:43,959: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-22 05:06:43,959: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1lsbWNngYHZMBuVfFr83-UcT0xKwVD8SN/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 05:12:05,069: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1lsbWNngYHZMBuVfFr83-UcT0xKwVD8SN/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 05:31:07,834: INFO: main: >>>>>> 01 - Stage 01 - Stage => Data Ingestion started. <<<<<<]
[2025-02-22 05:31:07,834: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 05:31:07,834: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 05:31:07,834: INFO: common: created directory at: artifacts]
[2025-02-22 05:31:07,841: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-22 05:31:07,843: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1lsbWNngYHZMBuVfFr83-UcT0xKwVD8SN/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 05:37:39,533: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1lsbWNngYHZMBuVfFr83-UcT0xKwVD8SN/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 05:38:01,760: INFO: main: >>>>>> 01 - Stage 01 - Stage => Data Ingestion completed. <<<<<<

x==========x]
[2025-02-22 06:04:57,143: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 06:04:57,147: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 06:04:57,150: INFO: common: created directory at: artifacts]
[2025-02-22 06:04:57,153: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-22 06:05:10,869: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-22 06:22:38,213: INFO: main: >>>>>> 01 - Stage => Data Ingestion started. <<<<<<]
[2025-02-22 06:22:38,215: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 06:22:38,215: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 06:22:38,215: INFO: common: created directory at: artifacts]
[2025-02-22 06:22:38,215: ERROR: main: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "C:\Users\DHARANEESH\My Projects\Disease Prediction\disease-prediction\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion_config = config.get_data_ingestion_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config'
[2025-02-22 06:24:26,567: INFO: main: >>>>>> 01 - Stage => Data Ingestion started. <<<<<<]
[2025-02-22 06:24:26,571: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 06:24:26,576: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 06:24:26,577: INFO: common: created directory at: artifacts]
[2025-02-22 06:24:26,577: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-22 06:24:26,579: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1lsbWNngYHZMBuVfFr83-UcT0xKwVD8SN/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 06:29:39,888: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1lsbWNngYHZMBuVfFr83-UcT0xKwVD8SN/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 06:30:03,615: INFO: main: >>>>>> 01 - Stage => Data Ingestion completed. <<<<<<

x==========x]
[2025-02-22 06:30:03,615: INFO: main: *******************]
[2025-02-22 06:30:03,615: INFO: main: >>>>>> 02 - Stage => Prepare Base Model started. <<<<<<]
[2025-02-22 06:30:03,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 06:30:03,620: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 06:30:03,621: INFO: common: created directory at: artifacts]
[2025-02-22 06:30:03,623: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-22 06:30:03,623: ERROR: main: name 'PrepareBaseModel' is not defined]
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    prepare_base_model.main()
  File "C:\Users\DHARANEESH\My Projects\Disease Prediction\disease-prediction\src\kidneyDiseaseClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model = PrepareBaseModel(config=prepare_base_model_config)
NameError: name 'PrepareBaseModel' is not defined
[2025-02-22 06:31:49,608: INFO: main: *******************]
[2025-02-22 06:31:49,608: INFO: main: >>>>>> 02 - Stage => Prepare Base Model started. <<<<<<]
[2025-02-22 06:31:49,612: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 06:31:49,613: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 06:31:49,616: INFO: common: created directory at: artifacts]
[2025-02-22 06:31:49,623: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-22 06:31:50,216: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-22 06:31:50,515: INFO: main: >>>>>> 02 - Stage => Prepare Base Model completed. <<<<<<

x==========x]
[2025-02-22 06:45:20,743: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 06:45:20,746: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 06:45:20,750: INFO: common: created directory at: artifacts]
[2025-02-22 06:45:20,752: INFO: common: created directory at: artifacts\training]
[2025-02-22 06:49:14,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 06:49:14,877: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 06:49:14,880: INFO: common: created directory at: artifacts]
[2025-02-22 06:49:14,881: INFO: common: created directory at: artifacts\training]
[2025-02-22 08:46:46,335: INFO: main: *******************]
[2025-02-22 08:46:46,335: INFO: main: >>>>>> 03 - Stage => Model Training started. <<<<<<]
[2025-02-22 08:46:46,335: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 08:46:46,342: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 08:46:46,342: INFO: common: created directory at: artifacts]
[2025-02-22 08:46:46,342: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model_trainer.main()
  File "C:\Users\DHARANEESH\My Projects\Disease Prediction\disease-prediction\src\kidneyDiseaseClassifier\pipeline\stage_03_model_training.py", line 15, in main
    training_config = config.get_training_config()
  File "c:\users\dharaneesh\my projects\disease prediction\disease-prediction\src\kidneyDiseaseClassifier\config\configuration.py", line 59, in get_training_config
    training_data = os.path.join(self.config.data_ingestion.unzip_dir, "CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone")
NameError: name 'os' is not defined
[2025-02-22 08:47:29,625: INFO: main: *******************]
[2025-02-22 08:47:29,625: INFO: main: >>>>>> 03 - Stage => Model Training started. <<<<<<]
[2025-02-22 08:47:29,641: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 08:47:29,641: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 08:47:29,641: INFO: common: created directory at: artifacts]
[2025-02-22 08:47:29,641: INFO: common: created directory at: artifacts\training]
[2025-02-22 08:48:16,172: INFO: main: *******************]
[2025-02-22 08:48:16,172: INFO: main: >>>>>> 03 - Stage => Model Training started. <<<<<<]
[2025-02-22 08:48:16,172: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 08:48:16,172: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 08:48:16,172: INFO: common: created directory at: artifacts]
[2025-02-22 08:48:16,172: INFO: common: created directory at: artifacts\training]
[2025-02-22 10:12:05,241: INFO: main: >>>>>> 03 - Stage => Model Training completed. <<<<<<

x==========x]
